[workspace]
members = [
    "spectrum-node",
    "spectrum-network",
    "spectrum-crypto",
    "spectrum-vrf",
    "algebra-core"
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true