[package]
name = "spectrum-vrf"
version = "0.1.0"
edition = "2021"
rust-version = "1.65.0"

[dependencies]
spectrum-crypto = { version = "0.1.0", path = "../spectrum-crypto" }
elliptic-curve = "0.13.*"
k256 = "0.13.*"